meta_product_name: "MOONSYC"
meta_title: "MOONSYC - Find the party you want, wherever you want "
meta_description: "Discover new events based on your taste"
meta_image: ""
twitter_account: ""   # required for Twitter Cards
