meta_product_name: "DEYZ"
meta_title: "DEYZ - music sharing platform "
meta_description: "Discover a new creative way to share your favorite music with your friends!"
meta_image: "cover_photo_deyz.png"
twitter_account: "@DeyzClub"   # required for Twitter Cards
